# Generated by Django 3.1.7 on 2021-03-15 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210315_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 3, 15, 16, 15, 40, 282440, tzinfo=utc)),
        ),
    ]
